[pytest]
pythonpath = .
asyncio_mode = auto
filterwarnings =
    ignore:'asyncio.get_event_loop_policy' is deprecated:DeprecationWarning
    ignore:'asyncio.set_event_loop_policy' is deprecated:DeprecationWarning
