"""baseline: drugs and prescription_records tables

Revision ID: 272aeb551e68
Revises:
Create Date: 2026-08-05 08:33:18.763138

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "272aeb551e68"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Requerido por la columna `drugs.embedding` (pgvector.sqlalchemy.Vector) — Alembic no
    # lo detecta automáticamente porque no forma parte de `Base.metadata`.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drugs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nregistro", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("pactivos", sa.String(), nullable=True),
        sa.Column("labtitular", sa.String(), nullable=True),
        sa.Column("cpres", sa.String(), nullable=True),
        sa.Column("documento_html", sa.String(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drugs_nombre"), "drugs", ["nombre"], unique=False)
    op.create_index(op.f("ix_drugs_nregistro"), "drugs", ["nregistro"], unique=True)
    op.create_table(
        "prescription_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.Text(), nullable=True),
        sa.Column("drugs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "advertencias", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "safety_check", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prescription_records")
    op.drop_index(op.f("ix_drugs_nregistro"), table_name="drugs")
    op.drop_index(op.f("ix_drugs_nombre"), table_name="drugs")
    op.drop_table("drugs")
    # ### end Alembic commands ###
